on:
  push:
    branches:
    - main
    
jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3.3.0
      with:
        ref: main
        lfs: true
        
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
  
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.0.0
      with:
        # Defining all the required inputs
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        use_godot_3: true

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Push Windows
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: within-the-vault
        ITCH_USER: variable-eye-games
        PACKAGE: ${{ steps.export.outputs.archive_directory }}/Windows Desktop.zip
        VERSION: ${{ steps.date.outputs.date }}
        
    - name: Push OSX
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: osx
        ITCH_GAME: within-the-vault
        ITCH_USER: variable-eye-games
        PACKAGE: ${{ steps.export.outputs.archive_directory }}/Mac OSX.zip
        VERSION: ${{ steps.date.outputs.date }}
    
    - name: Push Linux
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: within-the-vault
        ITCH_USER: variable-eye-games
        PACKAGE: ${{ steps.export.outputs.archive_directory }}/LinuxX11.zip
        VERSION: ${{ steps.date.outputs.date }}
