on:
  push:
    branches:
    - main
    
jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3.3.0
      with:
        ref: main
        lfs: true
        
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Get Version File
      run: echo ${{ steps.date.outputs.date }} > ./VERSIONFILE
  
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.0.0
      with:
        # Defining all the required inputs
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        use_godot_3: true
      
    - name: Push To Itch
      uses: Ayowel/butler-to-itch@v1.0.0
      with:
        butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
        itch_user: variable-eye-games
        itch_game: within-the-vault
        version: ${{ steps.date.outputs.date }}
        files: |
          win ${{ steps.export.outputs.archive_directory }}/Within The Vault - Windows.zip
          osx ${{ steps.export.outputs.archive_directory }}/Within The Vault - osx.zip
          linux ${{ steps.export.outputs.archive_directory }}/Within The Vault - Linux.zip
